name: Update F-Droid Repo
on:
  push:
    branches:
      - main

permissions:
  pages: write
  contents: write

jobs:
  update-fdroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup fdroidserver
        run: pip install fdroidserver

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
